net = alexnet;

net.Layers

layersTransfer = net.Layers(1:end-3);

numClasses = numel(categories(imdsTrain.Labels))
layers = [
    layersTransfer
    fullyConnectedLayer(numClasses,'WeightLearnRateFactor',20,'BiasLearnRateFactor',20)
    softmaxLayer
    classificationLayer];

options = trainingOptions('sgdm',...
    'MiniBatchSize',64,...
    'MaxEpochs',14,...
    'InitialLearnRate',1e-3,...
    'Shuffle','every-epoch',...
    'Plots','training-progress',...
    'ValidationData',imdsValidation,...
    'ValidationFrequency',32, ...
    'VerboseFrequency', 32,...
    'ValidationPatience',Inf, ...
    'ExecutionEnvironment','gpu');

[netTransfer, infoTraining] = trainNetwork(imdsTrain,layers,options);

[YPred,scores] = classify(netTransfer,imdsPrediction);

YValidation = imdsPrediction.Labels;
accuracy = mean(YPred == YValidation)