net = vgg19;

net.Layers

layersTransfer = net.Layers(1:end-3);
inputSize = net.Layers(1).InputSize;

numClasses = numel(categories(imdsTrain.Labels))
layers = [
    layersTransfer
    fullyConnectedLayer(numClasses,'WeightLearnRateFactor',20,'BiasLearnRateFactor',20)
    softmaxLayer
    classificationLayer];

pixelRange = [-30 30];
imageAugmenter = imageDataAugmenter( ...
    'RandXReflection',true, ...
    'RandXTranslation',pixelRange, ...
    'RandYTranslation',pixelRange);
augimdsTrain = augmentedImageDatastore(inputSize(1:2),imdsTrain, ...
    'DataAugmentation',imageAugmenter);

augimdsValidation = augmentedImageDatastore(inputSize(1:2),imdsValidation);
augimdsPrediction = augmentedImageDatastore(inputSize(1:2),imdsPrediction);

options = trainingOptions('sgdm',...
    'MiniBatchSize',64,...
    'MaxEpochs',14,...
    'InitialLearnRate',1e-3,...
    'Shuffle','every-epoch',...
    'Plots','training-progress',...
    'ValidationData',augimdsValidation,...
    'ValidationFrequency',32, ...
    'VerboseFrequency', 32,...
    'ValidationPatience',Inf, ...
    'ExecutionEnvironment','gpu');

[netTransfer, infoTraining] = trainNetwork(augimdsTrain,layers,options);

[YPred,scores] = classify(netTransfer,augimdsPrediction);

YValidation = imdsPrediction.Labels;
accuracy = mean(YPred == YValidation)